# Generated by Django 5.0.3 on 2024-05-11 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_image_url_alter_post_last_viewed_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='last_viewed_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 17, 32, 3, 463618)),
        ),
    ]
